target("mms-live-server", function ()
    set_kind("binary")
    add_files("**.cpp")
    add_deps("mms-base")
    add_deps(
        "mms-http",
        "mms-mp4",
        "mms-rtmp",
        "mms-rtp",
        "mms-rtsp",
        "mms-sdp",
        "mms-ts"
    )
    add_deps("mms-codec")
    add_deps("mms-http-sdk")
    add_deps("mms-server")

    add_packages(
        "spdlog",
        "boost",
        "yaml-cpp",
        "jsoncpp",
        "boringssl",
        "zlib",
        "libopus",
        "faac",
        "faad2",
        "ffmpeg",
        "srtp",
        "hiredis",
        "redis-plus-plus"
    )
end)
